src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CarRepository::class)]
class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $prix_location = null;

    #[ORM\Column]
    private ?float $prix_day = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $seat = null;

    #[ORM\Column(length: 255)]
    private ?string $gearbox = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrixLocation(): ?float
    {
        return $this->prix_location;
    }

    public function setPrixLocation(float $prix_location): static
    {
        $this->prix_location = $prix_location;

        return $this;
    }

    public function getPrixDay(): ?float
    {
        return $this->prix_day;
    }

    public function setPrixDay(float $prix_day): static
    {
        $this->prix_day = $prix_day;

        return $this;
    }

    public function getSeat(): ?int
    {
        return $this->seat;
    }

    public function setSeat(int $seat): static
    {
        $this->seat = $seat;

        return $this;
    }

    public function getGearbox(): ?string
    {
        return $this->gearbox;
    }

    public function setGearbox(string $gearbox): static
    {
        $this->gearbox = $gearbox;

        return $this;
    }

}

src/Form/CarType.php
<?php

namespace App\Form;

use App\Entity\Car;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Event\PreSubmitEvent;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\String\Slugger\AsciiSlugger;

class CarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                "label" => "Nom de la voiture"
            ])
            ->add('description', TextareaType::class, [
                "label" => "Description"
            ])
            ->add('prix_location', NumberType::class, [
                "label" => "Prix mensuel"
            ])
            ->add('prix_day', NumberType::class, [
                "label" => "Prix journalier"
            ])
            ->add('seat', ChoiceType::class, [
                "choices" => [
                    "1" => 1,
                    "2" => 2,
                    "3" => 3,
                    "4" => 4,
                    "5" => 5,
                    "6" => 6,
                    "7" => 7,
                    "8" => 8,
                    "9" => 9,
                ],
                "label" => "Nombre de places"
            ])
            ->add('gearbox', ChoiceType::class, [
                "choices" => [
                    "Manuelle" => "Manuelle",
                    "Automatique" => "Automatique"
                ],
                "label" => "Boîte de vitesse"
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Car::class,
        ]);
    }
}

src/Controller/Admin/CarController.php
<?php

namespace App\Controller\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Car;
use App\Form\CarType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;

#[Route('/admin/car')]
class CarController extends AbstractController
{
    #[Route('/create', name: 'createCar', methods: ["GET", "POST"])]
    public function new(Request $request, EntityManagerInterface $em)
    {
        $car = new Car();
        $form = $this->createForm(CarType::class, $car);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($car);
            $em->flush();
            $this->addFlash("success", "Vous avez ajouté une nouvelle voiture");
            return $this->redirectToRoute("home");
        }

        return $this->render('admin/car/createCar.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/{id}/delete', name: "deleteCar", methods: ["DELETE"])]
    public function delete(Car $car, EntityManagerInterface $em)
    {
        $em->remove($car);
        $em->flush();
        $this->addFlash("success", "La voiture a bien été supprimée");
        return $this->redirectToRoute("home");
    }
}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Repository\CarRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
// use App\Entity\Car;

class CarController extends AbstractController
{
    // #[Route('/addcar', name: 'addcar', methods: ['GET', 'POST'])]
    // public function addCar(Request $request, CarRepository $carRepository): Response
    // {
    //     $car = new Car();
    //     $form = $this->createForm(CarType::class, $car);

    //     return $this->render('car/addcar.html.twig');
    // }

    #[Route('/showcar/{id}', name: 'showcar')]
    public function showCar(Request $request, CarRepository $carRepository, int $id): Response
    {
        $car = $carRepository->find($id);

        if (!$car) {
            return $this->redirectToRoute("home");
        }

        return $this->render('car/showcar.html.twig', [
            'car' => $car
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\CarRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(CarRepository $respository): Response
    {
        $cars = $respository->findAll();
        return $this->render('home/index.html.twig', [
            "cars" => $cars
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<title>
			{% block title %}Véhicloc
			{% endblock %}
		</title>
		<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
		{% block stylesheets %}
			<link rel="stylesheet" href="/assets/css/style.css">
		{% endblock %}

		{% block javascripts %}
			{% block importmap %}
				{{ importmap('app') }}
			{% endblock %}
		{% endblock %}

	</head>
	{% include "header.html.twig" %}
	<body>
		{% block body %}{% endblock %}
	</body>
	{% include "footer.html.twig" %}
</html>

templates/car/showcar.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une voiture
{% endblock %}

{% block body %}
	<section id="car">
		<a href="{{ path("home") }}">← Retour</a>
		<h1>{{ car.name }}</h1>

		<p class="description-car">{{ car.description }}</p>

		<div class="advantages">
			<div class="single-advantage"><img src="/assets/icons/checked.png" alt=""/>
				Km illimités</div>
			<div class="single-advantage"><img src="/assets/icons/checked.png" alt=""/>
				Taxe routière incluse</div>
			<div class="single-advantage"><img src="/assets/icons/checked.png" alt=""/>
				Assistance dépannage 24/7</div>
			<div class="single-advantage"><img src="/assets/icons/checked.png" alt=""/>
				Pas de frais caché</div>
			<div class="single-advantage"><img src="/assets/icons/checked.png" alt=""/>
				Assurance au tiers</div>
			<div class="single-advantage"><img src="/assets/icons/checked.png" alt=""/>
				Réservation sécurisée</div>
		</div>

		<hr>

		<p class="legal-information">Les conducteurs doivent avoir leur permis de conduire depuis au moins 5 ans.</p>

		<div class="total-rent">
			<span>Total</span>
			<span>{{ car.prixLocation|number_format(2) }}€/mois</span>
		</div>
		<button class="btn-add">Louer pour
			{{ car.prixLocation }}/mois</button>
		<!-- Bouton inactif -->
	</section>

	<section id="insurances">
		<h2>Les Assurances et Assistances</h2>

		<div class="insurances-list">
			<div class="single-insurance">
				<img src="/assets/icons/basic.png" alt="Basique"/>
				<h3>Protection Basique</h3>
				<p><img src="/assets/icons/checked.png" alt=""/>
					Assurance dommages pour les dommages par collision, les rayures, les chocs et le vol.</p>
			</div>
			<div class="single-insurance">
				<img src="/assets/icons/complete.png" alt="Complète"/>
				<h3>Protection Complète</h3>
				<p><img src="/assets/icons/checked.png" alt=""/>
					Assurance dommages pour les dommages par collision, les rayures, les chocs et le vol.</p>
				<p><img src="/assets/icons/checked.png" alt=""/>
					Protection pneus et vitres.</p>
			</div>
		</div>
	</section>

{% endblock %}

templates/footer.html.twig
<footer>
	<h2>Conduire avec nous</h2>
	<nav>
		<ul>
			<li>
				<a href="#">Mentions légales</a>
			</li>
			<li>
				<a href="#">Nous contacter</a>
			</li>
			<li>
				<a href="#"><img src="/assets/icons/instagram.png" alt="Instagram"/></a>
				<a href="#"><img src="/assets/icons/facebook.png" alt="Facebook"/></a>
			</li>
		</ul>
		<ul>
			<li>
				<a href="#">Données personnelles</a>
			</li>
			<li>
				<a href="#">Questions fréquentes</a>
			</li>
			<li class="copyright">© Véhicloc 2023</li>
		</ul>
	</nav>
</footer>

templates/header.html.twig
<header>
	<nav>
		<a href="{{ path('home') }}"><img src="/assets/img/logo.png" alt="Vehicloc"/></a>
		<a href="{{ path('createCar') }}" class="btn-nav">Ajouter une voiture</a>
	</nav>
	<div class="flex-header">
		<div>
			<h1>Location de voitures à Saint-Étienne</h1>
			<p>Un service de location de voitures au mois pour répondre à vos besoins de mobilité.</p>
		</div>
		<div>
			<img src="/assets/img/car.png" alt="Voiture">
		</div>
	</div>
</header>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!
{% endblock %}

{% block body %}
	<section id="fleet">
		<h2>Découvrez la flotte de véhicules chez Véhicloc</h2>
		<p>Que vous ayez besoin d'une petite citadine agile, d'une berline élégante ou même d'un SUV spacieux, nous avons une variété de véhicules  pour répondre à vos exigences.</p>
		<div class="fleet-list">
			{% for car in cars %}
				<article>
					<div class="mini-car-title">
						<a href="{{ path('showcar', {id: car.id}) }}">
							<h3>{{ car.name }}</h3>
							<p>ou similaire | Saint-Étienne</p>
						</a>
						<div>
							<form action="{{ path('deleteCar', {id: car.id}) }}" method="POST">
								<input type="hidden" name="_method" value="DELETE">
								<button type="submit"><img src="/assets/icons/trash.png" alt="Supprimer"/></button>
							</form>
						</div>
					</div>
					<div class="mini-car-icons">
						<div>
							<img src="/assets/icons/persons.png" alt="4 places"/>
							<p>{{ car.seat }}
								places</p>
						</div>
						<div>
							<img src="/assets/icons/motor.png" alt="Manuelle"/>
							<p>{{ car.gearbox }}</p>
						</div>
						<div>
							<img src="/assets/icons/km.png" alt="km illimités"/>
							<p>Km illimités</p>
						</div>
						<div>
							<img src="/assets/icons/plus.png" alt="PLus"/>
							<p>Plus</p>
						</div>
					</div>
					<div class="mini-car-price">
						<p class="price-per-day">{{ car.prixDay }}
							€ / jour</p>
						<p class="price-per-month">{{ car.prixLocation|number_format(2) }}
							€ / mois</p>
					</div>
				</article>
			{% endfor %}

		</div>
	</section>
{% endblock %}